// <auto-generated />
namespace ELearningProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_add_tablecolumn_contactınformation_back : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_add_tablecolumn_contactınformation_back));
        
        string IMigrationMetadata.Id
        {
            get { return "202311061222029_mig_add_tablecolumn_contactınformation_back"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
